config/routes.rb
Rails.application.routes.draw do

  root 'bookmark_manager#home'

  get 'add' => 'bookmarks#new'
  get 'search' => 'bookmark_manager#search'
  get 'bkmk' => 'bookmarks#index'
  resources :tags
  resources :bookmarks

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
	VALID_URL_REGEX = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\Z/ix
	validates :url, presence: true, length: { maximum: 255 }, format: { with: VALID_URL_REGEX }
	validates :title, presence: true, length: { maximum: 255 }
	validates :tag, length: { maximum: 255 }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmark_manager_controller.rb
class BookmarkManagerController < ApplicationController
	def home
	end

	def add
		@bookmark = Bookmark.new
	end

	def search
	end

	def bkmk
	end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
  	@bookmark = Bookmark.new
  end

  def index
    if params[:tag].present?
     @bookmarks = Bookmark.where({:tag => "#{params[:tag]}"})
    else
  	 @bookmarks = Bookmark.all
    end
  end

  def create
  	@bookmark = Bookmark.new(bk_params)
  	if @bookmark.save
  		redirect_to :back
  	else
  		render 'new'
  	end
  end

  private
  	def bk_params
  		params.require(:bookmark).permit(:url, :title, :tag)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_manager_helper.rb
module BookmarkManagerHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmark_manager/home.html.erb
<div class="center jumbotron">
	<h1>Bookmark Manager Deluxe</h1>

	<table>
		<tr>
			<td><%= link_to "View Bookmarks", bkmk_path, class: "btn btn-lg btn-primary" %></td>
			<td><%= link_to "Add Bookmark", add_path, class: "btn btn-lg btn-primary" %></td>
			<td><%= link_to "Search By Tag", search_path, class: "btn btn-lg btn-primary" %></td>
		</tr>
	</table>
</div>

app/views/bookmarks/index.html.erb
<div class="center jumbotron">
	<h1>Bookmarks</h1>

	<table>
	<% @bookmarks.each do |bk| %>
		<tr>
			<td><%= link_to bk.title, bk.url, class: "btn btn-lg btn-primary" %></td>
			<td><button type="button">Remove</button></td>
		</tr>
	<% end %>
	</table>

	
</div>
<form action="/bkmk" method="get">Search by Tag:<br><input type="text" name="tag"><br><input type="submit" value="Search"></form>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@bookmark) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control' %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :tag %>
      <%= f.text_field :tag, class: 'form-control' %>

      <%= f.submit "Create bookmark", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookmarkManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @bookmark.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@bookmark.errors.count, "error") %>.
    </div>
    <ul>
    <% @bookmark.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>